### ISSUE TITLE
ModuleNotFoundError - matplotlib

### ISSUE THREAD

**Issue by sumepati** [aicoe-aiops/cloud-price-analysis-public#25]
**Describe the bug**
While executing notebook "cloud-price-analysis-EDA" cell 1, getting error as ModuleNotFoundError
ModuleNotFoundError: No module named 'matplotlib'

**To Reproduce**
1. Go to:- cloud-price-analysis-public-2022-02-21-09-51/notebooks/experimental/cloud-price-analysis-EDA
2. Click on:- Cell 1 and execute
3. See error as
"---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a2e9779eea04> in <module>
      1 import pandas as pd
----> 2 import matplotlib.pyplot as plt
      3 from collections import defaultdict

ModuleNotFoundError: No module named 'matplotlib'"

**Expected behavior**
Cell should get executed and required modules to get loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/82141673/154932663-38865c56-ab4e-4c31-83d0-467b8dabeacc.png)

**Additional context**
NA

**Comment by aakankshaduggal** [comment]
Hey @sumepati 
Thank you for creating this issue. You might want to run `pipenv install` to install all the required libraries. If you think some library is missing, please feel free to add a PR with the updated pipfile.

**Comment by sumepati** [comment]
Hi @MichaelClifford,
I'm seeing this error in "cloud-price-analysis" notebook image on the opf jupyterhub environment?
